# Generated by Django 5.2.4 on 2025-07-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adityaLMSUser',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=100)),
                ('userType', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='adityaAPPUpload',
            fields=[
                ('courseUpload', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('courseDescription', models.CharField(max_length=500)),
                ('createdAt', models.DateField()),
                ('coursePlaylist', models.IntegerField()),
                ('couseDuretion', models.IntegerField(max_length=10)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adityaAPP.adityaLMSuser')),
            ],
        ),
    ]
