# Generated by Django 5.2.4 on 2025-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adityaAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adityaLMSUser',
            new_name='adityaAPPUser',
        ),
        migrations.AlterField(
            model_name='adityaappupload',
            name='couseDuretion',
            field=models.IntegerField(),
        ),
    ]
